# Generated by Django 3.2.7 on 2021-09-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='blog_by_author',
            field=models.CharField(default='Akshay', max_length=50),
        ),
    ]
