# Generated by Django 3.2.7 on 2021-09-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
