# Generated by Django 3.2.7 on 2021-09-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='blog_by_author',
            field=models.CharField(max_length=50),
        ),
    ]
